          import cloudscraper
          import os

          file_path = "playlist.m3u"
          proxy_base = "https://backdor-proxy.onrender.com/proxy?link="
          url = "https://vjackson.info/live/index?output=json"
          
          scraper = cloudscraper.create_scraper()
          try:
              response = scraper.get(url, timeout=60)
              if response.status_code == 200:
                  channels = response.json()
                  with open(file_path, "w", encoding="utf-8") as f:
                      f.write("#EXTM3U\n")
                      count = 0
                      for ch in channels:
                          name = ch.get('name', '').upper()
                          group = ch.get('group', '')
                          ch_url = ch.get('url', '')
                          
                          # FİLTRE: Türkiye kanalları VEYA isminde "BEIN" geçen her şey
                          if group == 'Turkey' or "BEIN" in name or "SPOR" in name:
                              f.write(f'#EXTINF:-1 group-title="{group}",{ch.get("name")}\n')
                              f.write(f"{proxy_base}{ch_url}\n")
                              count += 1
                  print(f"Basarili: {count} kanal eklendi.")
              else:
                  print(f"Sunucu Hatasi: {response.status_code}")
          except Exception as e:
              print(f"Hata olustu: {e}")
              
